Handle console colors using tput or fallback to special prefixes

diff --git a/tools/hilbert-station b/tools/hilbert-station
--- a/tools/hilbert-station
+++ b/tools/hilbert-station
@@ -169,28 +169,31 @@ function cmd_start_locking() { ## @fn Start a lock to avoid parallel execution o
 }
 
 ## The following is due to https://en.wikipedia.org/wiki/ANSI_escape_code
-#declare -rg ANSI_GREEN='\033[0;32m'
-declare -rg ANSI_GRAY='\033[0;37m'
-declare -rg ANSI_CYAN='\033[1;36m'
-declare -rg ANSI_YELLOW='\033[1;33m'
-declare -rg ANSI_RED='\033[1;31m'
-declare -rg ANSI_BRIGHT_MAGENTA='\033[1;95m'
-declare -rg ANSI_BRIGHT_WHITE='\033[1;97m'
-declare -rg ANSI_NO_COLOR='\033[0m'
+## https://unix.stackexchange.com/questions/9957/how-to-check-if-bash-can-print-colors
+## https://linux.101hacks.com/ps1-examples/prompt-color-using-tput/
+if [[ -t 1 && -n "$(${TPUT} colors 2>/dev/null)" && "$(${TPUT} colors 2>/dev/null)" -ge 8 ]]; then
+    declare -rg ANSI_NO_COLOR="$(${TPUT} sgr0)" # '\033[0m'
+    declare -rg ANSI_RED="$(${TPUT} setaf 1)" # '\033[1;31m'
+    declare -rg ANSI_YELLOW="$(${TPUT} setaf 3)" # '\033[1;33m'
+    declare -rg ANSI_BRIGHT_MAGENTA="$(${TPUT} setaf 5)" # '\033[1;95m'
+    declare -rg ANSI_CYAN="$(${TPUT} setaf 6)" # '\033[1;36m'
+    declare -rg ANSI_GRAY="$(${TPUT} dim)$(${TPUT} setaf 7)" # '\033[0;37m'
+#    declare -rg ANSI_BRIGHT_WHITE="$(${TPUT} setaf 7)" # '\033[1;97m'
+fi
 
 # default colors for the logging routines:
-declare -rg COLOR_DEBUG="${COLOR_DEBUG:-${ANSI_GRAY}}"
-declare -rg COLOR_INFO="${COLOR_INFO:-${ANSI_CYAN}}"
-declare -rg COLOR_WARNING="${COLOR_WARNING:-${ANSI_YELLOW}}"
-declare -rg COLOR_ERROR="${COLOR_ERROR:-${ANSI_RED}}"
-declare -rg COLOR_DRYRUN="${COLOR_DRYRUN:-${ANSI_BRIGHT_MAGENTA}}"
-
+declare -rg COLOR_DEBUG="${HILBERT_CONSOLE_COLOR_DEBUG:-${ANSI_GRAY:-=== }}"
+declare -rg COLOR_INFO="${HILBERT_CONSOLE_COLOR_INFO:-${ANSI_CYAN:-    }}"
+declare -rg COLOR_WARNING="${HILBERT_CONSOLE_COLOR_WARNING:-${ANSI_YELLOW:-!!! }}"
+declare -rg COLOR_ERROR="${HILBERT_CONSOLE_COLOR_ERROR:-${ANSI_RED:-??? }}"
+declare -rg COLOR_DRYRUN="${HILBERT_CONSOLE_COLOR_DRYRUN:-${ANSI_BRIGHT_MAGENTA:-DRY }}"
+declare -rg COLOR_NONE="${HILBERT_CONSOLE_COLOR_NONE:-${ANSI_NO_COLOR:-}}"
 
 function DRYRUN_ECHO() {
     local _cmd="$@"
     if [[ $LOGLEVEL -le 2 ]]; then ## like a WARNING!
         local MSG=" ${DRY_RUN} [${TOOL}:${FUNCNAME[1]}] Simulating: [${_cmd}]"
-        ${PRINTF} "${COLOR_DRYRUN}${MSG}${ANSI_NO_COLOR}\n" 1>&2
+        ${PRINTF} "${COLOR_DRYRUN}${MSG}${COLOR_NONE}\n" 1>&2
         ${LOGGER} -p user.debug "${MSG}" 1>/dev/null 2>&1
     fi
     return ${ERR_CODE_SUCCESS}
@@ -208,7 +211,7 @@ function DRYRUN() {
         # NOTE: the following is to get proper function name!
         if [[ $LOGLEVEL -le 2 ]]; then ## like a WARNING!
             local MSG=" ${DRY_RUN} [${TOOL}:${FUNCNAME[1]}] Simulating: [${_cmd}]"
-            ${PRINTF} "${COLOR_DRYRUN}${MSG}${ANSI_NO_COLOR}\n" 1>&2
+            ${PRINTF} "${COLOR_DRYRUN}${MSG}${COLOR_NONE}\n" 1>&2
             ${LOGGER} -p user.debug "${MSG}" 1>/dev/null 2>&1
         fi
     fi
@@ -218,7 +221,7 @@ function DRYRUN() {
 function DEBUG() {
     if [[ $LOGLEVEL -le 0 ]]; then
         local MSG="DEBUG   [${TOOL}:${FUNCNAME[1]}] $*"
-        ${PRINTF} "${COLOR_DEBUG}${MSG}${ANSI_NO_COLOR}\n"
+        ${PRINTF} "${COLOR_DEBUG}${MSG}${COLOR_NONE}\n"
         ${LOGGER} -p user.debug "${MSG}" 1>/dev/null 2>&1
     fi
     return ${ERR_CODE_SUCCESS}
@@ -226,7 +229,7 @@ function DEBUG() {
 function INFO() {
     if [[ $LOGLEVEL -le 1 ]]; then
         local MSG="INFO    [${TOOL}:${FUNCNAME[1]}] $*"
-        ${PRINTF} "${COLOR_INFO}${MSG}${ANSI_NO_COLOR}\n"
+        ${PRINTF} "${COLOR_INFO}${MSG}${COLOR_NONE}\n"
         ${LOGGER} -p user.info "${MSG}" 1>/dev/null 2>&1
     fi
     return ${ERR_CODE_SUCCESS}
@@ -234,7 +237,7 @@ function INFO() {
 function WARNING() {
     if [[ $LOGLEVEL -le 2 ]]; then
         local MSG="WARNING [${TOOL}:${FUNCNAME[1]}] $*"
-        ${PRINTF} "${COLOR_WARNING}${MSG}${ANSI_NO_COLOR}\n" 1>&2
+        ${PRINTF} "${COLOR_WARNING}${MSG}${COLOR_NONE}\n" 1>&2
         ${LOGGER} -p user.warning "${MSG}" 1>/dev/null 2>&1
     fi
     return ${ERR_CODE_SUCCESS}
@@ -243,7 +246,7 @@ function WARNING() {
 function ERROR() {
     if [[ $LOGLEVEL -le 3 ]]; then
         local MSG="ERROR   [${TOOL}:${FUNCNAME[1]}] $*"
-        ${PRINTF} "${COLOR_ERROR}${MSG}${ANSI_NO_COLOR}\n" 1>&2
+        ${PRINTF} "${COLOR_ERROR}${MSG}${COLOR_NONE}\n" 1>&2
         ${LOGGER} -p user.err "${MSG}" 1>/dev/null 2>&1
     fi
     return ${ERR_CODE_INT_ERROR}
